<?php
/**
 * WebhookType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coachbox\Services\Polar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Polar Accesslink API
 *
 * Polar Accesslink API documentation
 *
 * OpenAPI spec version: 3.28.0
 * Contact: b2bhelpdesk@polar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Coachbox\Services\Polar\Models;
use \Coachbox\Services\Polar\ObjectSerializer;

/**
 * WebhookType Class Doc Comment
 *
 * @category Class
 * @description Event type to subscribe. Currently only EXERCISE supported.
 * @package  Coachbox\Services\Polar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhookType
{
    /**
     * Possible values of this enum
     */
    const EXERCISE = 'EXERCISE';
const ACTIVITY_SUMMARY = 'ACTIVITY_SUMMARY';
const PHYSICAL_INFORMATION = 'PHYSICAL_INFORMATION';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXERCISE,
self::ACTIVITY_SUMMARY,
self::PHYSICAL_INFORMATION,        ];
    }
}
