<?php
/**
 * ExerciseHashIdTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coachbox\Services\Polar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Polar Accesslink API
 *
 * Polar Accesslink API documentation
 *
 * OpenAPI spec version: 3.28.0
 * Contact: b2bhelpdesk@polar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Coachbox\Services\Polar;

/**
 * ExerciseHashIdTest Class Doc Comment
 *
 * @category    Class
 * @description Training session summary data
 * @package     Coachbox\Services\Polar
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExerciseHashIdTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExerciseHashId"
     */
    public function testExerciseHashId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "upload_time"
     */
    public function testPropertyUploadTime()
    {
    }

    /**
     * Test attribute "polar_user"
     */
    public function testPropertyPolarUser()
    {
    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "calories"
     */
    public function testPropertyCalories()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "heart_rate"
     */
    public function testPropertyHeartRate()
    {
    }

    /**
     * Test attribute "training_load"
     */
    public function testPropertyTrainingLoad()
    {
    }

    /**
     * Test attribute "sport"
     */
    public function testPropertySport()
    {
    }

    /**
     * Test attribute "has_route"
     */
    public function testPropertyHasRoute()
    {
    }

    /**
     * Test attribute "club_id"
     */
    public function testPropertyClubId()
    {
    }

    /**
     * Test attribute "club_name"
     */
    public function testPropertyClubName()
    {
    }

    /**
     * Test attribute "detailed_sport_info"
     */
    public function testPropertyDetailedSportInfo()
    {
    }
}
