<?php
/**
 * PhysicalInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coachbox\Services\Polar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Polar Accesslink API
 *
 * Polar Accesslink API documentation
 *
 * OpenAPI spec version: 3.28.0
 * Contact: b2bhelpdesk@polar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Coachbox\Services\Polar;

/**
 * PhysicalInformationTest Class Doc Comment
 *
 * @category    Class
 * @description User&#x27;s physical information
 * @package     Coachbox\Services\Polar
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PhysicalInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PhysicalInformation"
     */
    public function testPhysicalInformation()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "polar_user"
     */
    public function testPropertyPolarUser()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "maximum_heart_rate"
     */
    public function testPropertyMaximumHeartRate()
    {
    }

    /**
     * Test attribute "resting_heart_rate"
     */
    public function testPropertyRestingHeartRate()
    {
    }

    /**
     * Test attribute "aerobic_threshold"
     */
    public function testPropertyAerobicThreshold()
    {
    }

    /**
     * Test attribute "anaerobic_threshold"
     */
    public function testPropertyAnaerobicThreshold()
    {
    }

    /**
     * Test attribute "vo2_max"
     */
    public function testPropertyVo2Max()
    {
    }

    /**
     * Test attribute "weight_source"
     */
    public function testPropertyWeightSource()
    {
    }
}
