<?php
/**
 * WebhooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Coachbox\Services\Polar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Polar Accesslink API
 *
 * Polar Accesslink API documentation
 *
 * OpenAPI spec version: 3.28.0
 * Contact: b2bhelpdesk@polar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.5
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Coachbox\Services\Polar;

use Coachbox\Services\Polar\Configuration;
use Coachbox\Services\Polar\ApiException;
use Coachbox\Services\Polar\ObjectSerializer;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Coachbox\Services\Polar
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createWebhook
     *
     * Create webhook.
     *
     */
    public function testCreateWebhook()
    {
    }

    /**
     * Test case for deleteWebhook
     *
     * Delete webhook.
     *
     */
    public function testDeleteWebhook()
    {
    }

    /**
     * Test case for getWebhook
     *
     * Get webhook.
     *
     */
    public function testGetWebhook()
    {
    }

    /**
     * Test case for updateWebhook
     *
     * Update webhook.
     *
     */
    public function testUpdateWebhook()
    {
    }
}
